#!/bin/bash

str=`acpi`
tm=`echo "$str" | cut -d ' ' -f 5 | cut -d ':' -f 1,2`
st=`echo "$str" | cut -d ',' -f 1 | cut -d ' ' -f 3`
pr=`echo "$str" | cut -d ' ' -f 4 | cut -d '%' -f 1`

if [ "$st" == "Charging" ];then
	icon=""
else
	 if (( $pr < 10 ));then
		icon=""
	elif (( $pr < 50 ));then 
		icon=""
	elif (( $pr < 75 ));then
		icon=""
	else 
		icon=""

	fi
fi	

echo "$icon $pr%  $tm"
